# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Success
  description: "Successful submission"
  icon: "check"
  tags:
    - Success

# Defines the structure of this component, as well as the default values
blueprint:
  description: Success.
  image_path: src/assets/images/bakery-shots/0A877B3D-EA91-4499-8614-B3E08E704307.jpg
  image_alt: Success illustration

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
