# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Success
  description: 'Successful submission'
  icon: 'check'
  tags:
    - Success

# Defines the structure of this component, as well as the default values
blueprint:
  description: Success.
  image_path: src/assets/images/bakery-shots/0A877B3D-EA91-4499-8614-B3E08E704307.jpg
  image_alt: Success illustration
  button:
    button_text: Back Home
    button_icon:
    button_link: /
    background_color: '#2d2d2d'
    hover_brightness: 0.85
    text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description:
    type: markdown
